name: Backend Tests

on: [push, pull_request]


jobs:
  test:
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-versions: [3.9.13, 3.10.10]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python ${{ matrix.python-versions }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-versions }}
      - name: Install libraries
        working-directory: ./src/back-end
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run unittests
        working-directory: ./src/back-end
        run: |
          python -m coverage run -m unittest discover --pattern=*tests.py
          python -m coverage report -mi
      - name: Run pep8 checks
        working-directory: ./src/back-end
        run: flake8 --exclude __pycache__,venv,.venv,env
